//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 5 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `cafe`.
    var cafe: RswiftResources.ImageResource { .init(name: "cafe", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `hamburger`.
    var hamburger: RswiftResources.ImageResource { .init(name: "hamburger", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `save_active`.
    var save_active: RswiftResources.ImageResource { .init(name: "save_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `save_inactive`.
    var save_inactive: RswiftResources.ImageResource { .init(name: "save_inactive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `search_icon`.
    var search_icon: RswiftResources.ImageResource { .init(name: "search_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.font` struct is generated, and contains static references to 12 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `OpenSans-Bold`.
    var openSansBold: RswiftResources.FontResource { .init(name: "OpenSans-Bold", bundle: bundle, filename: "OpenSans-Bold.ttf") }

    /// Font `OpenSans-BoldItalic`.
    var openSansBoldItalic: RswiftResources.FontResource { .init(name: "OpenSans-BoldItalic", bundle: bundle, filename: "OpenSans-BoldItalic.ttf") }

    /// Font `OpenSans-ExtraBold`.
    var openSansExtraBold: RswiftResources.FontResource { .init(name: "OpenSans-ExtraBold", bundle: bundle, filename: "OpenSans-ExtraBold.ttf") }

    /// Font `OpenSans-ExtraBoldItalic`.
    var openSansExtraBoldItalic: RswiftResources.FontResource { .init(name: "OpenSans-ExtraBoldItalic", bundle: bundle, filename: "OpenSans-ExtraBoldItalic.ttf") }

    /// Font `OpenSans-Italic`.
    var openSansItalic: RswiftResources.FontResource { .init(name: "OpenSans-Italic", bundle: bundle, filename: "OpenSans-Italic.ttf") }

    /// Font `OpenSans-Light`.
    var openSansLight: RswiftResources.FontResource { .init(name: "OpenSans-Light", bundle: bundle, filename: "OpenSans-Light.ttf") }

    /// Font `OpenSans-LightItalic`.
    var openSansLightItalic: RswiftResources.FontResource { .init(name: "OpenSans-LightItalic", bundle: bundle, filename: "OpenSans-LightItalic.ttf") }

    /// Font `OpenSans-Medium`.
    var openSansMedium: RswiftResources.FontResource { .init(name: "OpenSans-Medium", bundle: bundle, filename: "OpenSans-Medium.ttf") }

    /// Font `OpenSans-MediumItalic`.
    var openSansMediumItalic: RswiftResources.FontResource { .init(name: "OpenSans-MediumItalic", bundle: bundle, filename: "OpenSans-MediumItalic.ttf") }

    /// Font `OpenSans-Regular`.
    var openSansRegular: RswiftResources.FontResource { .init(name: "OpenSans-Regular", bundle: bundle, filename: "OpenSans-Regular.ttf") }

    /// Font `OpenSans-SemiBold`.
    var openSansSemiBold: RswiftResources.FontResource { .init(name: "OpenSans-SemiBold", bundle: bundle, filename: "OpenSans-SemiBold.ttf") }

    /// Font `OpenSans-SemiBoldItalic`.
    var openSansSemiBoldItalic: RswiftResources.FontResource { .init(name: "OpenSans-SemiBoldItalic", bundle: bundle, filename: "OpenSans-SemiBoldItalic.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [openSansBold, openSansBoldItalic, openSansExtraBold, openSansExtraBoldItalic, openSansItalic, openSansLight, openSansLightItalic, openSansMedium, openSansMediumItalic, openSansRegular, openSansSemiBold, openSansSemiBoldItalic].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 13 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `OpenSans-Bold.ttf`.
    var openSansBoldTtf: RswiftResources.FileResource { .init(name: "OpenSans-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-BoldItalic.ttf`.
    var openSansBoldItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-BoldItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-ExtraBold.ttf`.
    var openSansExtraBoldTtf: RswiftResources.FileResource { .init(name: "OpenSans-ExtraBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-ExtraBoldItalic.ttf`.
    var openSansExtraBoldItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-ExtraBoldItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Italic.ttf`.
    var openSansItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-Italic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Light.ttf`.
    var openSansLightTtf: RswiftResources.FileResource { .init(name: "OpenSans-Light", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-LightItalic.ttf`.
    var openSansLightItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-LightItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Medium.ttf`.
    var openSansMediumTtf: RswiftResources.FileResource { .init(name: "OpenSans-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-MediumItalic.ttf`.
    var openSansMediumItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-MediumItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Regular.ttf`.
    var openSansRegularTtf: RswiftResources.FileResource { .init(name: "OpenSans-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-SemiBold.ttf`.
    var openSansSemiBoldTtf: RswiftResources.FileResource { .init(name: "OpenSans-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-SemiBoldItalic.ttf`.
    var openSansSemiBoldItalicTtf: RswiftResources.FileResource { .init(name: "OpenSans-SemiBoldItalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `vendors.json`.
    var vendorsJson: RswiftResources.FileResource { .init(name: "vendors", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }
}